global:
  storageClass: longhorn

# Run in production mode behind NGINX proxy terminating TLS sessions
production: true
# ref: https://www.keycloak.org/server/reverseproxy
proxyHeaders: xforwarded

# Admin user
auth:
  adminUser: admin

postgres:
  enabled: false

externalDatabase:
  host: "postgresql-ha-pgpool.keycloak.svc.cluster.local"
  port: 5432
  user: "postgres"
  password: null
  existingSecret: "postgresql-secret"
  existingSecretPasswordKey: "TVRBNE1HRmpNekkyTkRjek56WTVZbUpoTTJFMU1HRXdaVEF5TlRoa05HSUs="
  database: "keycloak"

persistence:
  enabled: true
  size: "8Gi"

# Ingress config
ingress:
  enabled: true
  ingressClassName: "nginx"
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Increasing proxy buffer size to avoid
    # https://stackoverflow.com/questions/57503590/upstream-sent-too-big-header-while-reading-response-header-from-upstream-in-keyc
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
  hostname: keycloak.saashq.org
  tls: true
